name: Unit tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.1
            
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.4

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test
